
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: %repo%
    restart: always
    ports:
      - "3046:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    
